/**
 * Export Manager - Handles various export formats and operations
 */

import { Editor } from '@tiptap/react';
import { serializeToCleanHTML, SerializerOptions, ExportResult, generateSchemaScript } from './HTMLSerializer';

export interface ExportOptions extends Partial<SerializerOptions> {
    format: 'html' | 'html-with-schema' | 'json' | 'markdown';
    filename?: string;
}

export interface FullExport {
    html: string;
    schemaScripts: string;
    combinedOutput: string;
    json: object;
    stats: ExportResult['stats'];
}

/**
 * Export content from Tiptap editor
 */
export function exportContent(editor: Editor, options: ExportOptions): FullExport {
    const jsonContent = editor.getJSON();

    const result = serializeToCleanHTML(jsonContent, {
        includeTOC: options.includeTOC ?? true,
        includeSchemaMarkup: options.includeSchemaMarkup ?? false,
        minify: options.minify ?? false,
        tocPosition: options.tocPosition ?? 'top',
    });

    // Generate schema scripts
    let schemaScripts = '';
    if (result.faqSchema) {
        schemaScripts += generateSchemaScript(result.faqSchema) + '\n';
    }
    // Note: Article schema would be generated here if we had page context

    // Combined output with schemas
    const combinedOutput = result.html + (schemaScripts ? '\n\n' + schemaScripts : '');

    return {
        html: result.html,
        schemaScripts,
        combinedOutput,
        json: jsonContent,
        stats: result.stats,
    };
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch (err) {
        // Fallback for older browsers
        try {
            const textArea = document.createElement('textarea');
            textArea.value = text;
            textArea.style.position = 'fixed';
            textArea.style.left = '-9999px';
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand('copy');
            document.body.removeChild(textArea);
            return true;
        } catch (e) {
            console.error('Failed to copy to clipboard:', e);
            return false;
        }
    }
}

/**
 * Download content as file
 */
export function downloadAsFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Generate Blogger-ready HTML with all required elements
 */
export function generateBloggerHTML(exportResult: FullExport): string {
    const header = `<!-- 
  Generated by Notion-Style Editor
  Include widget.js for interactive features
  Stats: ${exportResult.stats.headings} headings, ${exportResult.stats.faqs} FAQs, ${exportResult.stats.wordCount} words
-->

`;

    const widgetNote = `
<!-- Add this before </body> in your Blogger template -->
<!-- <script src="https://your-cdn.com/widget.js"></script> -->
`;

    return header + exportResult.html + widgetNote;
}

export default exportContent;
